name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['23.x']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage to SonarCloud
        if: ${{ env.SONAR_TOKEN != '' && env.SONAR_ORG != '' && env.SONAR_PROJECT != '' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          SONAR_PROJECT: ${{ secrets.SONAR_PROJECT }}
        run: |
          npx sonarqube-scanner \
            -Dsonar.organization=${SONAR_ORG} \
            -Dsonar.projectKey=${SONAR_PROJECT} \
            -Dsonar.sources=src \
            -Dsonar.tests=__tests__ \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info


